// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkani.DAL;

#nullable disable

namespace PlakaDukkani.DAL.Migrations
{
    [DbContext(typeof(PlakDukkaniContext))]
    [Migration("20230129094807_a1")]
    partial class a1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Album", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Typname", "nvarchar");

                    b.Property<string>("AlbumSanatcisi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Typname", "nvarchar");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CıkısTarihi")
                        .HasColumnType("datetime2")
                        .HasAnnotation("Typname", "datetime");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Typname", "money");

                    b.Property<decimal>("Indirim")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Typname", "money");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SatisDevami")
                        .HasColumnType("int");

                    b.Property<int>("YoneticiID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YoneticiID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Yonetici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AdiSoyadi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Typname", "nvarchar");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Typname", "nvarchar");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasAnnotation("Typname", "nvarchar");

                    b.HasKey("ID");

                    b.ToTable("Yoneticis");
                });

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Album", b =>
                {
                    b.HasOne("PlakDukkani.Entities.Concrete.Yonetici", "Yonetici")
                        .WithMany("Albums")
                        .HasForeignKey("YoneticiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("PlakDukkani.Entities.Concrete.Yonetici", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
